# These artifacts provide a workaround related to Application Router and Automated Credential Rotation
# ! A restart of Application Router will enforce a re-authentication of all active users !
# ! Please make sure to read the respective issue in the central README document first !
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-susaas-onboarding-router
  namespace: default
spec:
  concurrencyPolicy: Forbid
  # Restart Deployment daily at 00:00 UCT
  schedule: '0 0 * * *'
  timeZone: "Etc/UTC"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      ttlSecondsAfterFinished: 10
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: deployment-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/susaas-onboarding-router'
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-restart
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart
subjects:
  - kind: ServiceAccount
    name: deployment-restart
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
  namespace: default
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch"]