global:
  imagePullSecret: {}
  domain: a1b2c3.kyma.ondemand.com
  shootName: a1b2c3 

router:
  image:  
    repository: sapdemo/susaas-router
    tag: latest

srv:
  image:
    repository: sapdemo/susaas-srv
    tag: latest

api:
  image:
    repository: sapdemo/susaas-api
    tag: latest

broker:
  image:
    repository: sapdemo/susaas-broker
    tag: latest
  config: 
    serviceId: 11111111-1111-1111-1111-111111111111
    plans:
      - name: default
        description: Standard Plan
        planId: 22222222-2222-2222-2222-222222222222
      - name: premium
        description: Premium Plan
        planId: 33333333-3333-3333-3333-333333333333
      - name: trial
        description: Trial Plan
        planId: 44444444-4444-4444-4444-444444444444

hana_deployer:
  image:
    repository: sapdemo/susaas-db-com
    tag: latest

html5_apps_deployer:
  image:
    repository: sapdemo/susaas-html5-deployer
    tag: latest

xsuaa:
  parameters:
   oauth2-configuration:
    redirect-uris:
      - https://*.a1b2c3.kyma.ondemand.com/**
      - http://*.localhost:5000/**
      - http://localhost:5000/**