kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace}}-aws-creds
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Release.Namespace}}-aws-creds
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws_secret_access_key }}
 {{- if .Values.aws_session_token }}
  AWS_SESSION_TOKEN: {{ .Values.aws_session_token }}
 {{- end }}
type: Opaque
