---
general:
  buildTool: 'mta'

service:
  stages:
    Build:
      credentialVariables:
        - name: "Catalog"
          credentialId: "susaas-catalog"
        - name: "XsSecurity"
          credentialId: "susaas-xs-security"
        - name: "AlertNotif"
          credentialId: "susaas-alert-notif"
      runFirst:
        command: |
          # Disable debug mode (turn off echo for all commands and variables)
          set +x

          echo "$Catalog" > ./code/broker/catalog-private.json

          echo "$XsSecurity" > ./deploy/cf/config/xs-security-private.json

          echo "$AlertNotif" > ./deploy/cf/config/alert-notif-private.json

          # Enable debug mode (echo commands and variables) again
          set -x
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    karmaExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    tmsUpload: true

steps:
  npmExecuteLint:
    failOnError: true

  mtaBuild:
    platform: 'CF'
    source: './deploy/cf/'
    extensions: './mtaext/free-basic-cicd.mtaext'
    ##### e.g., './mtaext/free-basic-cicd.mtaext'
    
  cloudFoundryDeploy:
    cfCredentialsId: susaas-cf-credentials
    apiEndpoint: 'https://api.cf.eu10-004.hana.ondemand.com'
    org: 'EngSrvVal-E2E_e2evalidation-c1qcerkh'
    space: 'nidhi'
    mtaDeployParameters: '-f --version-rule ALL'
    mtaExtensionDescriptor: './deploy/cf/mtaext/free-basic-cicd.mtaext'
    ################# e.g., './deploy/cf/mtaext/free-basic-cicd.mtaext'
    mtaExtensionCredentials: 
      susaas-sb-credentials: susaas-sb-credentials
    

tmsUpload:  # only relevant once you finish the SAP Cloud Transport Management Expert Feature chapter
  nodeName: 'TEST'
  credentialsId: 'tms'
  customDescription: 'TMS Upload'
