global:
  imagePullSecret: {}
  domain: a1b2c3.kyma.ondemand.com
  shootName: a1b2c3 

srv:
  image:
    repository: sap-demo/susaas-obd-srv
    tag: latest
  bindings:
    saas-registry:
      serviceInstanceFullname: susaas-saas-registry
  env: 
    OBD_APP_NAME : susaas
    OBD_APPLICATION_IDP : sap-demo.accounts.ondemand.com
    OBD_GLOBACCT: sap-demo
    OBD_NAMESPACE : default
    OBD_PARENT_DIR : 00000000-a1b2-c3d4-e5f6-00000000000
    OBD_PLATFORM_IDP : sap-demo.accounts.ondemand.com
    OBD_REGION : eu10
    OBD_SHOOTNAME : a1b2c3
    OBD_SAAS_ADMINS : '["saas.admin@example.org","saas.admin2@example.org"]'
    OBD_SUBACCOUNT_ADMINS : '["subaccount.admin@example.org","subaccount.admin2@example.org"]'
    OBD_TERRAFORM_IMAGE: sap-demo/susaas-obd-terraform
    OBD_VIEWER_ROLE : "false"

router:
  image:
    repository: sap-demo/susaas-obd-router
    tag: latest

html5_apps_deployer:
  image:
    repository: sap-demo/susaas-obd-html5-deployer
    tag: latest

postgresql_db:
  # servicePlanName: trial
  parameters:
    allow_access: 12.345.678.90,09.876.543.21
