# SaaS API Workload
# Add this to the "api" module of your values-private.yaml file
api:
  # Service Key required for secure SAP API Management integration
  serviceKeys:
    xsuaa-apim:
      serviceInstanceName: xsuaa-api
  # Settings for SAP API Management integration
  apim:
    # SAP API Management runtime host w/o "https://" or port
    # e.g., <ProviderSubaccountSubdomain>.prod.apimanagement.<ProviderSubaccountRegion>.hana.ondemand.com
    host: sap-demo.prod.apimanagement.eu10.hana.ondemand.com
    # Port of SAP API Management runtime host
    port: 443
    # SAP API Management API Proxy Path (default - susaas-api)
    path: susaas-api
    # Provide details of the API XSUAA Service Instance
    # Those details can be found in the respective Kyma Secret
    # The Secret is created for the xsuaa-apim serviceKey
    xsuaa: 
      # Provide the XSUAA tenant URL of Provider Subaccount in the following format
      # e.g., <ProviderSubaccountSubdomain>.authentication.<ProviderSubaccountRegion>.hana.ondemand.com
      host: sap-demo.authentication.eu10.hana.ondemand.com
      # Provide the Client ID of your API XSUAA Service Instance in the following format
      # e.g., sb-<ReleaseName>-api-<Namespace>
      sub: sb-susaas-api-default