apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "obd-router.fullname" . }}
  labels: {{- include "obd-router.labels" . | nindent 4 }}
spec:
  selector: 
    matchLabels: {{- include "obd-router.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals: 
          - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account