{{- if hasKey .Values.serviceAccount "roleBinding" }}
{{- if or (not (hasKey .Values.serviceAccount.roleBinding "enabled")) .Values.serviceAccount.roleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "obd-srv.fullname" . }}
  labels: {{- include "obd-srv.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "obd-srv.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  name: {{ include "obd-srv.fullname" . }}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}