{{- if or (not (hasKey .Values.serviceAccount "enabled")) .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obd-srv.fullname" . }}
  labels: {{- include "obd-srv.labels" . | nindent 4 }}
{{- end }}