# Permissions for onboarding process
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "obd-srv.fullname" . }}
  labels: {{- include "obd-srv.labels" . | nindent 4 }}
rules:
- apiGroups: ['batch']
  resources: ['jobs']
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ['batch']
  resources: ['jobs/status']
  verbs:
  - get
  - list
- apiGroups: ["gateway.kyma-project.io"]
  resources: ["apirules"]
  verbs:
  - get
  - list