{{- if .Values.apim }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "susaas-api.fullname" . }}
  labels: {{- include "susaas-api.labels" . | nindent 4 }}
spec:
  action: ALLOW
  selector:
    matchLabels: {{- include "susaas-api.selectorLabels" . | nindent 6 }}
  rules:
  - from:
    - source:
        principals: 
          - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
        requestPrincipals: 
          - {{ printf "https://%s/oauth/token/%s!*" .Values.apim.xsuaa.host .Values.apim.xsuaa.sub }}
{{- end }}