apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "susaas-broker.fullname" . }}
  labels: {{- include "susaas-broker.labels" . | nindent 4 }}
spec:
  selector: 
    matchLabels: {{- include "susaas-broker.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals: 
          - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account