{{- if or (not (hasKey .Values.identity "enabled")) .Values.identity.enabled }}
  {{- $defaultParameters := dict "parameters" (
          include "template-value" ( dict "value" .Values.identity.parameters "context" . ) | fromYaml
      )
  }}
  {{- include "cap.service-instance" (mergeOverwrite (dict "defaultParameters" $defaultParameters.parameters "useDefaults" true ) .) }}
{{- end }}