general:
  buildTool: "docker"
  containerRegistryUrl: "https://registry.hub.docker.com"
  containerImageName: "susaas-srv"
  containerImageTag: "latest"

service:     
  Release:
      kubeConfigSecretTextCredentialsId: "susaas-kube-config"
      helmValuePath: "./deploy/kyma/charts/sustainable-saas/values.yaml"
      helmValueSecret: "susaas-kyma-values-yaml"

stages:
  Build:
    kanikoExecute: false
  Acceptance:
    kubernetesDeploy: false
  Release:
    kubernetesDeploy: true                        
    deployTool: "helm3"
    namespace: "<Namespace>"  
    #### e.g., "default"
    chartPath: "./deploy/kyma/charts/sustainable-saas"
    deploymentName: "<ReleaseName>"
    ######### e.g., "susaas-prod"
    force: true