_schema-version: '3.2'
ID: susaas-obd
version: 0.0.1

parameters:
  deploy_mode: html5-repo
  enable-parallel-deployments: true
  autoscalerMinInstance: 1
  autoscalerMaxInstance: 2

build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm install --include=dev --prefix=../../code
        - npx -p @sap/cds-dk cds build -in ../../code --profile production

modules:
  # --------------------- APPROUTER MODULE ---------------------
  - name: susaas-obd
  # ------------------------------------------------------------
    type: approuter.nodejs
    path: ../../code/router
    build-parameters:
      builder: npm
      ignore: [ '.DS_Store', 'node_modules/', 'default-env.json', 'manifest*.yml' ]
    parameters:
      app-name: susaas-obd-${space}
      disk-quota: 256MB
      memory: 128MB
      keep-existing-routes: true
    requires:
      - name: susaas-obd-html5-repo-runtime
      - name: susaas-obd-srv-api
        group: destinations
        properties:
          name: susaas-obd-srv-api
          url: "~{srv-url}"
          forwardAuthToken: true
          timeout: 1800000
      - name: susaas-obd-ias
        parameters:
          config: 
             credential-type: X509_GENERATED
    provides:
      - name: susaas-obd-router-api
        properties:
           app-url: ${default-uri}


  # ------------------ TERRAFORM CONTAINER -----------------------
  - name: susaas-obd-terraform
    # ------------------------------------------------------------
    type: application
    build-parameters:
      no-source: true
    parameters:
      app-name: susaas-obd-terraform-${space}
      docker:
        image: ""
      health-check-type: process
      no-start: true 
      no-route: true
    provides:
      - name: susaas-obd-terraform-api
        properties:
           app-name: ${app-name}


  # ------------------- HTML5 APP DEPLOYER ---------------------
  - name: susaas-obd-app-deployer
    # ------------------------------------------------------------
    type: com.sap.html5.application-content
    path: ../../code/app/html5-deployer
    build-parameters:
      ignore: [".DS_Store", "node_modules/", "manifest*.yml"]
    requires:
      - name: susaas-obd-html5-repo-host


  # --------------------- UI MODULES ----------------------------
  #
  # ------------------------------------------------------------
  - name: sapsusaasobduihome
    type: html5
    path: ../../code/app/ui-home
    build-parameters:
      build-result: dist
      builder: custom
      ignore: [ 'node_modules/',  'default-env.json', 'manifest*.yml' ]
      commands:
      - npm run build
      - npm run copy
      supported-platforms: []
  
  - name: sapsusaasobduionboarding
    type: html5
    path: ../../code/app/ui-onboarding
    build-parameters:
      build-result: dist
      builder: custom
      ignore: [ 'node_modules/',  'default-env.json', 'manifest*.yml' ]
      commands:
      - npm run build
      - npm run copy
      supported-platforms: []
  

  # --------------------- SERVER MODULE ------------------------
  - name: susaas-obd-srv
  # ------------------------------------------------------------
    type: nodejs
    path: ../../code/gen/srv
    build-parameters:
      builder: npm
      ignore: [ '.DS_Store', 'node_modules/', 'default-*.json', 'manifest*.yml']
    parameters:
      app-name: susaas-obd-srv-${space}
      memory: 256MB
      disk-quota: 1024MB
      command: node ./node_modules/@sap/cds/bin/cds-serve
    properties:
      terraformName: ~{susaas-obd-terraform-api/app-name}
    requires:
      - name: susaas-credstore
        parameters:
          config:
            authorization:
              default_permissions:
                - read
                - decrypt
                - encrypt
                - list
      - name: susaas-registry
      - name: susaas-obd-html5-repo-runtime
      - name: susaas-obd-router-api
      - name: susaas-obd-terraform-api
      - name: susaas-obd-postgresql-db
      - name: susaas-obd-autoscaler
        parameters:
          config:
            instance_min_count: 1
            instance_max_count: 2
            scaling_rules:
            - {"metric_type": "memoryutil","threshold": 80,"operator": ">=","adjustment": "+1"}
            - {"metric_type": "memoryutil","threshold": 60,"operator": "<","adjustment": "-1"}
            - {"metric_type": "cpu","threshold": 80,"operator": ">=","adjustment": "+1"}
            - {"metric_type": "cpu","threshold": 30,"operator": "<","adjustment": "-1"}
      - name: susaas-obd-ias
        parameters:
          config: 
             credential-type: X509_GENERATED
    provides:
      - name: susaas-obd-srv-api
        properties:
          srv-url: ${default-url}

resources:
  # --------------------- REGISTRY SERVICE ---------------------
  - name: susaas-registry
  # ------------------------------------------------------------
    type: org.cloudfoundry.existing-service
    parameters:
      service-name: ${space}-susaas-registry
      
  # ----------------- CREDENTIAL STORE -------------------
  - name: susaas-credstore
  # ------------------------------------------------------
    active: true
    type: org.cloudfoundry.existing-service
    parameters:
      service-name: ${space}-susaas-credstore


  # ----------------- HTML REPO HOST SERVICE (Be Used by UI) ---------  
  - name: susaas-obd-html5-repo-host
  # -----------------------------------------------------------------
    type: org.cloudfoundry.managed-service
    parameters:
      service-plan: app-host
      service-name: ${space}-susaas-obd-html5-repo-host
      service: html5-apps-repo
      config:
        sizeLimit: 2

  # ----------------- HTML REPO RUNTIME SERVICE(Be Used by UI) -------
  - name: susaas-obd-html5-repo-runtime
  # ------------------------------------------------------------------
    type: org.cloudfoundry.managed-service
    parameters:
      service-plan: app-runtime
      service-name: ${space}-susaas-obd-html5-repo-runtime
      service: html5-apps-repo

  # ----------------- AUTOSCALER  ------------------------------------   
  - name: susaas-obd-autoscaler
  # ------------------------------------------------------------------
    type: org.cloudfoundry.managed-service
    parameters:
      service: autoscaler
      service-name: ${space}-susaas-obd-autoscaler
      service-plan: standard

  # ----------------- POSTGRESQL-DB ----------------------------------   
  - name: susaas-obd-postgresql-db
  # ------------------------------------------------------------------
    type: org.cloudfoundry.managed-service
    parameters:
      service: postgresql-db
      service-name: ${space}-susaas-obd-postgresql-db
      service-plan: free
      config:
        engine_version: "13"

  # ----------------- SAP IAS APPLICATION ---------------------------
  - name: susaas-obd-ias
  # ------------------------------------------------------------------
    type: org.cloudfoundry.managed-service
    requires:
      - name: susaas-obd-router-api
    parameters:
      service: identity
      service-name: ${space}-susaas-obd-ias
      service-plan: application
      config:
        display-name: Susaas-Onboarding-${space}-${org}
        oauth2-configuration:
          redirect-uris:
            - https://~{susaas-obd-router-api/app-url}/login/callback?authType=ias
          post-logout-redirect-uris: 
            - https://~{susaas-obd-router-api/app-url}/logout/**
          grant-types: ["authorization_code"]
          credential-types: ["binding-secret","x509"]
        xsuaa-cross-consumption: false
        multi-tenant: false