apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-btp-admin
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "cap.labels" ( merge (dict "name" "srv" ) .) | nindent 4 }}
type: Opaque
data:
  BTP_ADMIN_USER: {{ .Values.global.btpadmin.username | b64enc | quote }}
  BTP_ADMIN_PASSWORD: {{ .Values.global.btpadmin.password | b64enc | quote }}