{{- if .Values.ha.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "susaas-srv.fullname" . }}
  labels: {{- include "susaas-srv.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.ha.pdb.minAvailable | default 1 }}
  selector:
    matchLabels: {{- include "susaas-srv.selectorLabels" . | nindent 6 }}
{{- end }}
